name: Deploy to AWS Lambda
on: push

permissions:
        contents: read
jobs:
    lambda:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.ACCESS_KEY_ID_ZEELZ }}
                aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_ZEELZ }}
                aws-region: "us-east-1"                

            - name: Deploy Lambda Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                function-name: randomizer
                code-artifacts-dir: .
                handler: app.handler
                runtime: python3
                # Add any additional inputs this action supports